# Generated by Django 5.0 on 2023-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_product_price_product_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
    ]
