# Generated by Django 5.0 on 2023-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.FloatField(null=True),
        ),
    ]
