# Generated by Django 5.0 on 2023-12-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
    ]
