# Generated by Django 5.0 on 2023-12-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_price_order_product_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
    ]
